### ISSUE TITLE
Data Panes 'Total File Size Changed' Size Wrong

### ISSUE THREAD

**Issue by Trick17Industries** [Unmanic/unmanic-plugins#103]
The size displayed by the graph is different than the size shown when you hover over the bar.

the difference grows bigger when the sizes grow:

https://forums.unraid.net/uploads/monthly_2021_09/1050924674_Screenshot2021-09-20193022.png.c48b3f1cfef19a35005e67211fbd6e29.png

**Comment by Josh5** [comment]
Resolved in 2f30f2224af3923afc378e3637687c590bf47c28
