### ISSUE TITLE
re-run a file

### ISSUE THREAD

**Issue by pennakira** [Unmanic/unmanic-plugins#104]
how do you re-run a file again if it already went through unmanic? I did a test and the file size with hw encode was a lot larger than software encode for h265. But it will not let me re-run the folder.

**Comment by Josh5** [comment]
The simple answer you cannot. I would say your best option is to manually run the FFmpeg command on that file.

Unmanic basically is setting up some rules of how you want your files to be. Once they are in that state, Unmanic leaves them alone.

Hope that helps and answers your question.

Feel free to join the Discord server if you have any more questions. GitHub is not really the place. (Discord invite link below)

https://unmanic.app/discord
