### ISSUE TITLE
Plugin Icon Missing - Remux Video Files

### ISSUE THREAD

**Issue by dalkain** [Unmanic/unmanic-plugins#113]
I know it's a silly 'bug' report, but the following plugin is missing an icon: Remux Video Files

**Comment by Josh5** [comment]
How does this look?

https://github.com/Unmanic/unmanic-plugins/blob/official/source/video_remuxer/icon.png

**Comment by Josh5** [comment]
Closing as I have made one tonight :)

**Comment by dalkain** [comment]
I think it looks great! 
The perpetually-loading gradient for missing icons keeps making me think something is broken on my end 😅
