### ISSUE TITLE
Plugin Icon Missing - Convert any ASS subtitle streams in videos to SRT

### ISSUE THREAD

**Issue by dalkain** [Unmanic/unmanic-plugins#114]
I know it's a silly 'bug' report, but the following plugin is missing an icon: Convert any ASS subtitle streams in videos to SRT

**Comment by Josh5** [comment]
Not at all a silly bug my friend.

I would be more than happy to accept a Pull Request for one if you would like to make it.

**Comment by dalkain** [comment]
![icon](https://user-images.githubusercontent.com/34625175/135211377-e1c15d78-4eb3-4615-920c-4e94bdec938b.png)
Not doing a pull request since I want you to decide if this fits within your design logic. 

I obviously reused content from your other icons, but without knowing the font I had to try and make the 'A' somewhat match. I've still got the layered file if you want to let me know the font and I can replace the 'ASS' text

**Comment by Josh5** [comment]
Looks awesome. You should make a pr

**Comment by Josh5** [comment]
Thanks!
