### ISSUE TITLE
PGS to SRT

### ISSUE THREAD

**Issue by turbalf** [Unmanic/unmanic-plugins#145]
Hello,
I have an issue in plex with PGS subtitle who makes direct play failing and transcode too hard for my qnap.
Is there a wy to get a plugin to remove PGS subtitle and convert them to srt ?
Thanks a lot !

**Comment by Josh5** [comment]
This is not something that is easily done. If you are able to execute a command from a Linux terminal that can do this for you, feel free to share it and I'll make a plugin to execute that command on all your files.

Untill then I'm closing this. Feel free to comment here once you have a working command.

**Comment by Nonobis** [comment]
Hello , maybe including the linux version of SubtitleEdit in plugins ?
https://github.com/SubtitleEdit/subtitleedit/releases

A use command line cal from plugins ?

**Comment by Josh5** [comment]
> Hello , maybe including the linux version of SubtitleEdit in plugins ?
> https://github.com/SubtitleEdit/subtitleedit/releases
> 
> A use command line cal from plugins ?
> 

Could you give me an example command line showing this working on a file with pgs subs from a Ubuntu terminal?

**Comment by Nonobis** [comment]
i am on windows but it must be relatively same command line ... i will rip a bluray with pgs and post commandline when it's working :)
