### ISSUE TITLE
Data not added to File Size Metric Data panels when using linked worker

### ISSUE THREAD

**Issue by m0dd3r43v3r** [Unmanic/unmanic-plugins#151]
I am testing the Link settings to be able to link 2 instances of Unmanic together and it seems to be working okay but I noticed that when the job completes on the sub workers it goes into the completed tasks on the primary but it does not appear in the File Size metrics data panel on either instances.

**Comment by Josh5** [comment]
Resolved in 2f30f2224af3923afc378e3637687c590bf47c28
