### ISSUE TITLE
[Extract text subtitle streams to SRT files v0.0.6] No attribute 'Settings' in v0.2.0

### ISSUE THREAD

**Issue by dalkain** [Unmanic/unmanic-plugins#225]
Since the v0.2.0 update, the following keeps popping up in my logs:

```
2022-03-14T15:40:07:ERROR:Unmanic.PluginExecutor - [FORMATTED] - module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 390, in save_plugin_settings

    plugin_settings = plugin_module.Settings(library_id=library_id)

AttributeError: module 'extract_srt_subtitles_to_files.plugin' has no attribute 'Settings'
```

Seems like a pretty straightforward error, since this doesn't have any configurable options, so I didn't really do any additional troubleshooting beyond a simple uninstall/reinstall. I assume it was just a simple oversight when migrating the plugin to the new multi-library plugin system.

EDIT: Okay, I know I have a really bad habit of editing my issues after submitting them, but I completely forgot to say that the plugin still functions and extracts the subtitles as expected.

**Comment by Josh5** [comment]
Thanks. You are quite right. The issues is with the main application rather than this plugin. The plugin, as you say, does not have any configuration options.

I have pushed a fix to stop this error showing in the logs
https://github.com/Unmanic/unmanic/commit/270442fdc7865ce535cd521a4644642f5231f239
