### ISSUE TITLE
[Bug]: File Size Metrics Data Panel

### ISSUE THREAD

**Issue by npendlington** [Unmanic/unmanic-plugins#310]
### Describe the Bug

After installing Unmanic v0.2.3~b517463 and v0.0.8 of the plugin, the Data Panel page just crashes with a message box and the error: 
`DataTables warning: table id=history_completed_tasks_table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`
The page then looks uninitialised and broken:
![image](https://user-images.githubusercontent.com/8480122/204287351-91f6580f-9182-48c8-b7a9-ea3aa39fb876.png)

### Version

v0.2.3~b517463

### Platform

UnRAID v6.11.1 docker container
Platform (Operating System):
Linux 915b24f3d99b 5.19.14-Unraid #1 SMP PREEMPT_DYNAMIC Thu Oct 6 09:15:00 PDT 2022 x86_64 x86_64
Python Version: 3.8.10.final.0

**Comment by Josh5** [comment]
Have you added the plugin to a library?

**Comment by npendlington** [comment]
@Josh5 I hadn't, no (still getting my head around Unmanic as it's the first time I've used it). Perhaps the data panel shouldn't show until it exists in at least one library? Or at least has some data.

I added the plugin to my two libraries (TV and Movies), and they seem to show up as post processing steps as expected.
Performed a rescan of my libraries which didn't make any difference, so I forced an update to a movie which triggered an encoding worker (this completed successfully)

The log for the job shows this though:
```RUNNER:
File Size Metrics Data Panel [Pass #1]
Executing plugin runner... Please wait
Runner did not request to execute a command

**Comment by Josh5** [comment]
> @Josh5 I hadn't, no (still getting my head around Unmanic as it's the first time I've used it). Perhaps the data panel shouldn't show until it exists in at least one library? Or at least has some data.
> 
Noted.

> Performed a rescan of my libraries which didn't make any difference, so I forced an update to a movie which triggered an encoding worker (this completed successfully)
> 
Is it now showing an entry in the table?

**Comment by npendlington** [comment]
No, it still doesn't seem to be working. Anything else I can do to get some diagnostics for you?

**Comment by Josh5** [comment]
Probably best to jump into the support Discord server and ask for help there. GitHub is more for reporting issues or requesting features.

https://unmanic.app/discord
