### ISSUE TITLE
Transcode files by filename

### ISSUE THREAD

**Issue by raysv** [Unmanic/unmanic-plugins#359]
### What is your new plugin request?

Hi, 
Would like to see a plugin that would only handle files that feks contains "Remux" in their filename.

This way i could setup different properties on the transcoding q and know that Remux's gets handled one way, and lets say WEB-DL with other settings. 

Right now i think the only way to make this happend is to keep remux, web-dl, webrips, hdtv etc in differents folders which is a pita.

**Comment by Josh5** [comment]
There is a plugin to ignore files by name in the library scan.

If you need help getting that setup, jump on Discord to the support channel.

**Comment by raysv** [comment]
That will work :) Overlooked that one for some reason!! Thanks!
