### ISSUE TITLE
Commercial detection / removal plugin (comskip)

### ISSUE THREAD

**Issue by IamRewt** [Unmanic/unmanic-plugins#40]
A plugin that can process commercials both for detection and marking or for removal.

**Comment by Josh5** [comment]
I've created a plugin for this in my development repo. I do not have any PVR recordings. Would you be able to test it for me?

You will need to add my repo URL to Unmanic:
```
https://raw.githubusercontent.com/Josh5/unmanic-plugins/repo/repo.json
```
![unmanic-adding-my-plugin-repo](https://user-images.githubusercontent.com/8370197/134129502-ed71fc20-2b69-45fa-b2c2-bd87abb7e6d8.png)

In there you will find a plugin named "Skip commercials in TV show - Comskip".

Look forward to hearing how you get on with this

**Comment by Josh5** [comment]
@IamRewt Just checking in to see if you saw this update?

**Comment by IamRewt** [comment]
@Josh5 Hi sorry for the delay I missed your initial comment. I'm excited to test this out for you! I will get this added to my container tomorrow and begin testing it.

I'll report back if I encounter any issues!

**Comment by IamRewt** [comment]
@Josh5 I am getting errors when attempting to run comskip. It looks like it might be related to some permissions to the script stored in the appdata folder for comchap/comcut. I am not sure if this is something I can correct on my end or if I have done something improperly.

I installed the plugin, created the .sh file with the script provided, chose to remove commercials in the settings, then restarted unmanic.

Here is a snip:
![comskip log](https://user-images.githubusercontent.com/89737602/134451559-9552b9d3-efe6-4424-9ebd-67385a0db26c.PNG)

**Comment by IamRewt** [comment]
Also, for safety, it may be a good idea to limit comskip so that it only runs on .ts files unless otherwise configured. As far as I know most tuners for emby/jellyfin/plex use .ts as the container for live tv.

It would probably cut down on processing time too. If not I can always spin up a second container and aim it at my DVR folder which would solve that just as well.

**Comment by Josh5** [comment]
Limiting it by file extension is a really good idea. I'll update the plugin to do this.

The errors look like it is missing the comskip config. Did you configure the plugin with your comskip.ini config?
If it isnt config, then yea, perhaps I need to ensure those files are executable with `chmod +x /path/to/comchap/comcut`

This is the comskip.ini config that I used when testing it out:
```
detect_method=255			;1=black frame, 2=logo, 4=scene change, 8=fuzzy logic, 16=closed captions, 32=aspect ration, 64=silence, 128=cutscenes, 255=all
validate_silence=1			; Default, set to 0 to force using this clues if selected above.
validate_uniform=1			; Default, set to 0 to force using this clues (like pure white frames) if blackframe is selected above.
validate_scenechange=1		; Default, set to 0 to force using this clues if selected above.
verbose=5				;show a lot of extra info, level 5 is also OK, set to 0 to disable
max_brightness=61      			;frame not black if any pixels checked are greater than this (scale 0 to 255)
test_brightness=41     		;frame not pure black if any pixels checked are greater than this, will check average brightness (scale 0 to 255)
max_avg_brightness=21			;maximum average brightness for a dim frame to be considered black (scale 0 to 255) 0 means autosetting
max_commercialbreak=310 		;maximum length in seconds to consider a segment a commercial break
min_commercialbreak=25			;minimum length in seconds to consider a segment a commercial break
max_commercial_size=150			;maximum time in seconds for a single commercial or multiple commercials if no breaks in between
min_commercial_size=3   		;mimimum time in seconds for a single commercial
min_show_segment_length=311 	; any segment longer than this will be scored towards show.
non_uniformity=40			; Set to 0 to disable cutpoints based on uniform frames
max_volume=250				; any frame with sound volume larger than this will not be regarded as black frame
min_silence=12				; Any deep silence longer than this amount  of frames is a possible cutpoint
ticker_tape=0				; Amount of pixels from bottom to ignore in all processing 
logo_at_bottom=0			; Set to 1 to search only for logo at the lower half of the video, do not combine with subtitle setting
punish=0					; Compare to average for sum of 1=brightness, 2=uniform 4=volume, 8=silence, 16=schange, set to 0 to disable
punish_threshold=1.3		; Multiply when amount is above average * punish_threshold
punish_modifier=2			; When above average * threshold multiply score by this value
intelligent_brightness=0 		; Set to 1 to use a USA specific algorithm to tune some of the settings, not adviced outside the USA
logo_percentile=0.92			; if more then this amount of logo is found then logo detection will be disabled
logo_threshold=0.75
punish_no_logo=1			; Default, set to 0 to avoid show segments without logo to be scored towards commercial
aggressive_logo_rejection=1
connect_blocks_with_logo=1		; set to 1 if you want successive blocks with logo on the transition to be regarded as connected, set to 0 to disable
logo_filter=4               ; set the size of the filter to apply to bad logo detection, 4 seems to be a good value.
cut_on_ar_change=0			; set to 1 if you want to cut also on aspect ratio changes when logo is present, set to 2 to force cuts on aspect ratio changes. set to 0 to disable
delete_show_after_last_commercial=0	; set to 1 if you want to delete the last block if its a show and after a commercial
delete_show_before_or_after_current=0	; set to 1 if you want to delete the previous and the next show in the recording, this can lead to the deletion of trailers of next show
delete_block_after_commercial=0	;set to max size of block in seconds to be discarded, set to 0 to disable 
remove_before=0				; amount of seconds of show to be removed before ALL commercials
remove_after=0				; amount of seconds of show to be removed after ALL commercials
shrink_logo=5				; Reduce the duration of the logo with this amount of seconds
after_logo=0		; set to number of seconds after logo disappears comskip should start to search for silence to insert an additional cutpoint
padding=0
ms_audio_delay=5
volume_slip=40
skip_b_frames=0				; Set to 1 to force Comskip to skip frames for higher processing speed.
max_repair_size=200			; Will repair maximum 200 missing MPEG frames in the timeline, set to 0 to disable repairing for players that don't use PTS. 
disable_heuristics=4		bit pattern for disabling heuristics, adding 1 disables heristics 1, adding 2 disables heristics 2, adding 4 disables heristics 3, 255  disables all heuristics 
delete_logo_file=1			; set to 1 if you want comskip to tidy up after finishing
output_framearray=1			; create a big excel file for detailed analysis, set to 0 to disable
output_debugwindow=1
output_data=0				; create a dump of the user data channel, used for CC and XDS (such as V-Chip info). Can be use together with output_framearray to remote debug CC decoding
output_videoredo=0
output_womble=0
output_mls=0			; set to 1 if you want MPeg Video Wizard bookmark file output
output_cuttermaran=0
output_mpeg2schnitt=0
output_mpgtx=0
output_dvrcut=0
output_zoomplayer_chapter=0
output_zoomplayer_cutlist=0
output_edl=1
output_edlx=0
output_vcf=0
output_bsplayer=0
output_btv=0				; set to 1 if you want Beyond TV chapter cutlist output
output_projectx=0			; set to 1 if you want ProjectX cutlist output (Xcl)
output_avisynth=0
output_vdr=0				; set to 1 if you want XBMC to skipping commercials
output_demux=0				; set to 1 if you want comskip to demux the mpeg file while scanning
sage_framenumber_bug=0
sage_minute_bug=0
live_tv=0					; set to 1 if you use parallelprocessing and need the output while recording
live_tv_retries=4			; change to 16 when using live_tv in BTV, used for mpeg PS and TS
dvrms_live_tv_retries=300			; only used for dvr_ms
standoff=0					; change to 8000000 when using live_tv in BTV
cuttermaran_options="cut=\"true\" unattended=\"true\" muxResult=\"false\" snapToCutPoints=\"true\" closeApp=\"true\""
mpeg2schnitt_options="mpeg2schnitt.exe /S /E /R25  /Z %2 %1"
avisynth_options="LoadPlugin(\"MPEG2Dec3.dll\") \nMPEG2Source(\"%s\")\n"
dvrcut_options="dvrcut \"%s.dvr-ms\" \"%s_clean.dvr-ms\" "
windowtitle="Comskip - %s"
edge_step=2
edge_radius=2
give_up_logo_search=30000
edge_level_threshold=2
length_strict_modifier=3.0
length_nonstrict_modifier=1.5
combined_length_strict_modifier=2.0
combined_length_nonstrict_modifier=1.25
logo_present_modifier=0.01
excessive_length_modifier=0.01
ar_wrong_modifier=2.0
min_schange_modifier=0.5
max_schange_modifier=2.0
schange_threshold=80
cc_commercial_type_modifier=4.0
cc_wrong_type_modifier=2.0
cc_correct_type_modifier=0.75
dictionary_modifier=1.05
global_threshold=1.05

```

**Comment by IamRewt** [comment]
I had not set up anything in the config box. I will just copy what you have to test it out. 
I have only used comskip in a non-configurable scenario till now, so I didn't realize this was even needed :)

**Comment by IamRewt** [comment]
So adding in the config you provided got rid of the plugin not configured error but I did still get the permission error. 

![comskip 2](https://user-images.githubusercontent.com/89737602/134456960-bad58ccc-1150-40f0-8015-6f0194c35035.PNG)

Is it possible for me to run the chmod command for that file/folder or will it need a plugin update?

I'll pick up testing tomorrow if possible. Just out of curiosity, if I select comcut or comchap in the settings for the plugins do I need to already have an edl file for the media? Or will the plugin generate the edl first and then run comchap or comcut?

**Comment by Josh5** [comment]
The plugin runs comskip to generate the edl file in accordance with your comskip.ini config file.

If you open a shell inside the container you can chmod 755 the file.
```
chmod 755 /config/.unmanic/plugins/conskip/comchap/comcut
```

I'll update the plugin to handle this

**Comment by IamRewt** [comment]
For today, I went ahead and ran:
chmod 755 /mnt/user/appdata/unmanic/.unmanic/plugins/conskip/comchap/comcut
I tried running the other command from the unmanic console, but it said no such file or directory was found.

After that, it seems like it was trying to run comskip, but it couldn't seem to do anything. Every file had the exact same log.
![comskip 3](https://user-images.githubusercontent.com/89737602/134557193-49dc19bf-1712-47b0-8dbc-309253671e09.PNG)

This is line 142 of the comcut file, in case it helps:
if [ ! -f "$edlfile" ]; then
  $comskipPath $comskipoutput --ini="$comskipini" "$infile"
fi

**Comment by Josh5** [comment]
How did you install comskip? Check that you are able to run comskip inside the container.

**Comment by IamRewt** [comment]
EDIT: Disregard this, I have everything working correctly now (I think) had 4 successful conversions then commercial removals. Going to erase unmanic, and start from scratch just to make sure I have all the steps I used to get going!

**Comment by Josh5** [comment]
Ok. Cool.

If there is any confusion in the required setup process, let me know. Perhaps it is better to include comskip in the official container build.

If a documented setup step was confusing and you think you have a better way of wording it, let me know.

**Comment by IamRewt** [comment]
Ok, the plugin does seem to do its job well, will continue testing and tuning the ini file for my preferences. In order to get it going, I needed to do the following:

1) Install the plugin and add the config.ini text
2) From the container console I manually installed comskip (apt-get update && apt-get install -y comskip)
     ---The startup.sh file didn't seem to run by itself for whatever reason.
3) I couldn't get the chmod commands to alter the permissions, so from windows, I changed the permissions for the comskip folder, the comchap folder, and the comcut file to give full control to Everyone, Users, and Nobody.

After doing all of that, the plugin works well. It makes the edl file, then cuts the commercials out for me!

Aside from fixing the permissions, the only other thing I would suggest is limiting the plugin by extensions. If we could have a textbox with a comma-separated list to search for such as: ts,mpg,mov etc. that would be cool!

**Comment by IamRewt** [comment]
I was thinking about suggesting having it included in the container, but I'm not sure if everyone would prefer that or not. Some may consider it bloat? For me, it would have made things a bit more simple. 
if it isn't included in the container, then maybe in the plugin description just say:

To install comskip (required) open a console window from the unraid container and type the following:
  apt-get update
  apt-get install -y comskip

In the end, it's just one of those things. After trial and error (and some helpful hints from you!), I got it going.

**Comment by Josh5** [comment]
The problem with installing it in the container is that when you update your container, it blows away the apt installation. The startup script is supposed to fix that by checking that it is installed on every container start.

I would prefer to leave it out of the docker image. 
I'll have a think about it.

**Comment by IamRewt** [comment]
Should the output of that script be visible in the unraid log for the container? If so I can attempt to tool around a bit with it to see if I can get it to run.

**Comment by Josh5** [comment]
yes when it is installing you will see it in your docker logs.

I will update the docs to say to put this in the script:
```
if ! command -v comskip &> /dev/null; then
    echo "**** Installing Comskip ****"
    apt-get update
    apt-get install -y comskip
else
    echo "**** Comskip already installed ****"
fi
```

This way you will see an output during container startup if it is already installed

**Comment by Josh5** [comment]
I've pushed an update.
The instructions now include the script defined above...
The plugin now ensures the 2 files comchap and comcut are executable
And the plugin now allows to filter based on file extension with a default of ts if you enable it.

**Comment by IamRewt** [comment]
Awesome, I'll pull it down today :)
Well because I made the script in windows, it didn't have UNIX line endings, correcting that allowed the script to run just fine!

One new problem though. The option to only run comskip on certain file extensions works well, however, because comskip needs to be run last, if the file has just been converted to another container, comskip cannot run on the file.

I did attempt to run comskip and then converting it to another container, but that did not work out very well. I'm not sure what to do about that one, to be honest.

**Comment by Josh5** [comment]
So you tried adding chapters with comchap to a TS file, then converting it to an mkv (or something)? Did the chapters not follow to the new container?

**Comment by IamRewt** [comment]
Well, it has only seemed to happen with .mpg files so far. I used comcut to remove commercials, then attempted to convert it to an mkv. It resulted in an mkv file that was corrupted and 0kb in size.

I did the same with a .ts file and that worked fine but did result in some extra files being created like a CSV file and ffmeta that did not get removed after the conversion was finished.

If I allow files to be converted to .mkv first and then run comcut, it doesn't seem to matter what kind of file it was initially and everything works properly, but in this case, I cannot tell comskip not to process .mkv files.

**Comment by Josh5** [comment]
I have an idea then... I'll make this change shortly...
What if we change it ever so slightly to say: "Only run when the original source file matches specified extensions"
Then, if we configure it with `ts,mov`, the plugin will only process files that were ORIGINALLY that extension. So that way you can convert it first to mkv/h264, then process the file with this plugin. And the plugin will still ignore files which were originally mkv or mp4 or whatever..

Edit:
Plugin updated to v0.0.4 with this change

**Comment by IamRewt** [comment]
That sounds perfect, I may not be able to test it too much today, but I will definitely try to run some recordings through it! 

Also, I pulled down the last update and the startup script did its job well. It checked for comskip, didn't have it, then downloaded it! :)

**Comment by Josh5** [comment]
Did you make any progress on testing it out?

**Comment by IamRewt** [comment]
Yes, just doing one more test after this but so far all is working well. If the file is in the allowed list, it will run comskip after the initial conversion to mkv now. It also ignores files that start off in containers not listed in the allowed list.

All in all, it seems to be working well! The only thing I would recommend now is maybe a disclaimer in the plugin description. When you do any update to the container the next startup will take a while as comskip will have to be re-installed.

EDIT: Do you have any specific scenarios you would like me to test for you?

**Comment by Josh5** [comment]
I've updated the docs as suggested.
I have actually removed the startup script from the docs. I'm updating the Docker container to auto-install this from the plugin so you don't need to manually create a `/config/startup.sh` script.

Going to make a PR to the official plugin repo for this and close this issue. Hope it all works out well for you!
