### ISSUE TITLE
Remux Video Plugin not working

### ISSUE THREAD

**Issue by CptChaz** [Unmanic/unmanic-plugins#64]
Remux Video Files plugin v-0.0.3 not changing container type from .mkv to .mp4 (hevc/ aac source).

**Comment by Josh5** [comment]
Does it have an error? If the plugin failed, it should show an error in the unmanic.log file

**Comment by CptChaz** [comment]
it's not showing an error, it's showing success. But you're right about the subtitles, this particular grouping does have them. They're also in an unusual format that I haven't seen before. 
<img width="971" alt="Screen Shot 2021-09-03 at 4 54 46 PM" src="https://user-images.githubusercontent.com/55520028/132068742-ea716072-5ad3-425b-8e61-bb30e58d73ad.png">

**Comment by Josh5** [comment]
I'm suspicious of the subtitles.
I'll PM you for more details. I may need to update the documentation to give better warning about this as this will be very common.

The dvd_subtitle format is an image subtitle format. I believe that mp4 does not support that subtitle format.

My suggestion would be to first remove these subs before remuxing

**Comment by Josh5** [comment]
Can you please update to the latest version of the plugin and test it.

Closing as it should be fixed with commit f01dc5618405e519caad7ac59002fe591e698217

Reopen this issue if problem persists.
